# Generated by Django 4.2.5 on 2024-07-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studen',
            new_name='Student',
        ),
    ]
